version: "2"
services:
  ui:
    image : dgoldstein1/websiteanalytics-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  server:
    image : dgoldstein1/websiteanalytics-backend
    environment:
      - LOGGER=true
      - TEST_MODE=false
      - DATABASE_URL=mongodb://mongodb:27017
      - PORT=5000
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - 5002:5000

  mongodb:
    image: 'mongo:4.0.5'